# Password ?? URL ?? ??????? ????? ???? ???????? (Security ?? ????)
spring.datasource.url=jdbc:postgresql://pg-1a27ecc7-asithasandaruwan044-7c98.a.aivencloud.com:24053/defaultdb?sslmode=require
spring.datasource.username=avnadmin
# Password ?? ???? ??????? ????. ??? ?? Render Environment Variable ??? ????.

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Settings
server.port=8080

# View Settings
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true